# This workflow will build and push a node.js application to an Aerobatic Web App when a release is created.
#
# To configure this workflow:
#
# 1. Set up a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE with the value of your Azure publish profile.
#
# 2. Change the values for the AZURE_WEBAPP_NAME, AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables  (below).
#
# For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
on:
  release:
    types: [created]

env:
  secure: ggpadUWUIDEnQJRfvqhbO2PGMey5/6dvnStMlGVFVgURsoDEY0B7rcg5dBc8dsFaK7qtRcomU59YSbgK6UaiPFcO+0zHaz7slTKMbkqV/a6S3AYh7CYGDRUN48wceFZ7KwuD7hDvfMMnxRq3cmbKUh/0fuoBii9ykxHmBV0LRiVbzlTPgPy/enPit8FcBoZ0Dt3pIWx1QIsha4AYSj1B81/XUcpBK67XGhqbanpIRA8GlwyhrvZM6KeHabY5atyXnqkyS5UycMASkvjistywzKbqkV6JrRdf9CtBZ8vJYohyqV+Vb1Vt36kRlNburpqSH18E02RvLO0ve2w8K7/P3GQ2W9yosTojpFSw3dLj0YwUbYwSp7CAvB3+tROXDKf9Shprs2dtusBMUTegGEVeetqliCjWEBm+8zvDybipPhcctvfxV+CynbiRfCbOo6fTSeBpxjUc+EXGAiaXRNshja7MEnUwk+B7/BOkmZMFcHC1lgYi29W+5ZA6eGiNBkU6mTu09bpSJc9uzMEzosTk1bArSTSeJQLyBj9EljErTWJSwgjRQz+Jhb1I/sHt2GLssEYKWxWjFh5ughOEvd2cjE3X5uzzn8KvPyO+zVThgLeeu+jyreWlyetxIteza4wdrZQCjpHfMibzdUxG1eD1q7CAlKpka/zaCkPxNBoqxU4=
  NODE_VERSION: '10.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        npm run build --if-present
        npm run test --if-present
    - name: 'Deploy to Aerobatic'
      uses: aerobatic/webapps-deploy@v2
      with:
        app-name: ${{ env.WEBAPP_NAME }}
        publish-profile: ${{ secrets.WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.WEBAPP_PACKAGE_PATH }}
